name: Build StripperCS2

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [created]

env:
  PREMAKE_VERSION: "5.0.0-beta2"
  HL2SDKCS2: ${{ github.workspace }}/hl2sdk
  MMSOURCE112: ${{ github.workspace }}/metamod-source

jobs:
  build:
    runs-on: ubuntu-24.04
        
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    # 下载HL2SDK-CS2
    - name: Download HL2SDK-CS2
      run: |
        git clone --depth=1 --branch=cs2 https://github.com/alliedmodders/hl2sdk.git
      
    - name: Download MetaMod:Source
      run: |
        git clone --depth=1 https://github.com/alliedmodders/metamod-source.git
        
    # Linux依赖
    - name: Download Premake5
      run: |
        wget https://github.com/premake/premake-core/releases/download/v${{ env.PREMAKE_VERSION }}/premake-${{ env.PREMAKE_VERSION }}-linux.tar.gz
        tar xvzf premake-${{ env.PREMAKE_VERSION }}-linux.tar.gz
        chmod +x premake5
        
    - name: Install Dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y gcc-multilib g++-multilib libc6-dev-i386

    # 构建依赖库
    - name: Build Dependencies
      run: |
        git submodule update --init --recursive
        
    # 生成项目文件
    - name: Generate Project Files
      run: |
        ./premake5 gmake2
        
    # 打包整个项目目录
    - name: Archive Project Directory
      run: |
        tar -czf StripperCS2_Project.tar.gz *
        
    # 上传项目目录压缩包
    - name: Upload Project Archive
      uses: actions/upload-artifact@v3
      with:
        name: StripperCS2_Project
        path: StripperCS2_Project.tar.gz

    # 尝试构建（即使失败也不影响上传）
    - name: Try Build
      continue-on-error: true
      run: |
        make -C build config=release_linux64 -j$(nproc)