name: Build StripperCS2

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [created]

env:
  PREMAKE_VERSION: "5.0.0-beta2"
  HL2SDKCS2: ${{ github.workspace }}/hl2sdk
  MMSOURCE112: ${{ github.workspace }}/metamod-source

jobs:
  build:
    runs-on: ubuntu-24.04
        
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    # 下载HL2SDK-CS2
    - name: Download HL2SDK-CS2
      run: |
        git clone --depth=1 --branch=cs2 https://github.com/alliedmodders/hl2sdk.git
      
    # 下载MetaMod:Source
    - name: Download MetaMod:Source
      run: |
        git clone --depth=1 https://github.com/alliedmodders/metamod-source.git
        
    # 安装Python和pip
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    # 安装AMBuild
    - name: Install AMBuild
      run: |
        git clone https://github.com/alliedmodders/ambuild.git
        cd ambuild
        pip install .
        cd ..
        
    # Linux依赖
    - name: Install Dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y gcc-multilib g++-multilib libc6-dev-i386

    # 生成项目文件并构建
    - name: Configure and Build
      run: |
        mkdir build && cd build
        python3 ../configure.py --enable-optimize
        ambuild

    # 检查并打包输出文件
    - name: Archive Output Files
      run: |
        mkdir -p output
        cp -r build/* output/
        tar -czf StripperCS2_Output.tar.gz output/

    # 上传构建产物
    - name: Upload Build Output
      uses: actions/upload-artifact@v4
      with:
        name: StripperCS2_Output
        path: StripperCS2_Output.tar.gz